paths:
  markdown_dir: "./markdown"    # Markdown文件目录
  html_dir: "./html"           # 生成的HTML文件目录
  log_dir: "./logs"           # 日志文件目录

logging:
  level: "DEBUG"              # 日志级别：DEBUG/INFO/WARNING/ERROR
  format: "detailed"          # 日志格式：simple/detailed
  save_days: 7               # 日志保留天数

link_fix:
  similarity_threshold: 0.8   # 文件名相似度阈值
  max_path_depth: 2          # 路径搜索深度
  auto_select: true          # 自动选择最可能的修复方案

watch:
  interval: "1d"             # 文件检查间隔（一天）
  patterns:                  # 监控的文件模式
    - "*.md"
    - "*.markdown" 